env:
  - GO111MODULE=on
  - GOPROXY=https://goproxy.io

before:
  hooks:
    - go mod download

builds:
  -
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - openbsd
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64

archives:
  -
    replacements:
      386: 32-bit
      amd64: 64-bit
      darwin: macos
    format_overrides:
      - goos: windows
        format: zip
    files:
      - ip.txt
      - README.md
      - config.json

checksum:
  name_template: 'checksums.txt'